# Generated by Django 3.2.7 on 2022-01-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdonemodels',
            old_name='Bisnis_success',
            new_name='Project_success',
        ),
    ]
