# Generated by Django 3.2.7 on 2022-01-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_bisnis_success_projectdonemodels_project_success'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projectDoneModels',
            new_name='projectDoneModel',
        ),
    ]
