# Generated by Django 3.2.7 on 2021-12-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('gamabar1', models.ImageField(blank=True, upload_to='content/gamar1')),
                ('gamabar2', models.ImageField(blank=True, upload_to='content/gamar2')),
                ('gamabar3', models.ImageField(blank=True, upload_to='content/gamar3')),
                ('kategori', models.CharField(max_length=50)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
