# Generated by Django 3.2.7 on 2021-12-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='gamabar1',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='gamabar2',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='gamabar3',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='gambar1',
            field=models.ImageField(blank=True, upload_to='content/gambar1'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='gambar2',
            field=models.ImageField(blank=True, upload_to='content/gambar2'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='gambar3',
            field=models.ImageField(blank=True, upload_to='content/gambar3'),
        ),
    ]
