# Generated by Django 3.2.7 on 2021-12-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectmodel_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='kategori',
            field=models.CharField(choices=[('Networking', 'Networking'), ('Design', 'Design'), ('Dekstop App', 'Dekstop App'), ('Mobile App', 'Mobile App'), ('Website', 'Website'), ('architect', 'architect')], max_length=50),
        ),
    ]
